name: Test and Deploy to PyPI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: pypi

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel twine
      - name: Bump version and create tag
        id: tag
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          echo "Bumping version..."
          current_version=$(python setup.py --version)
          echo "Current version: $current_version"
          new_version=$(python -c "from packaging.version import Version; ver=Version('$current_version'); print(f'{ver.major}.{ver.minor + 1}.0')")
          echo "New version: $new_version"
          sed -i "s/version=\"$current_version\"/version=\"$new_version\"/" setup.py
          git config --global user.email "gabrielbramos@outlook.com"
          git config --global user.name "Gabriel Martinusso"
          git commit -am "Bump version to $new_version"
          git tag "v$new_version"
          git push https://$GH_PAT@github.com/gmartinu/django-ts-exporter.git main --tags
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
