name: Test and Deploy to PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover tests

  deploy:
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    needs: test
    environment: pypi

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel twine
      - name: Create tag
        id: tag
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating tag..."
          current_version=$(python setup.py --version)
          echo "Current version: $current_version"
          git config --global user.email "gabrielbramos@outlook.com"
          git config --global user.name "Gabriel Martinusso"
          git tag "v$current_version"
          git push https://$GH_PAT@github.com/gmartinu/django-ts-exporter.git main --tags
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
